### ISSUE TITLE
Serial write

### ISSUE THREAD

**Issue by tom-eilers-nl** [a10036gt/EV3-SPIKE_Sensor_Adapter-Staff#1]
If you look at the qyro sensor block reset, there is a input serial write.  

Maybe you can use this in your block to:

It's not possible control the LEDs on SPIKE/RI Color and Ultra Sonic Sensor in EV3 Environment, Since it use write command with CMD_WRITE_DATA, this function is omitted on EV3. Unless rebuild the EV3 firmware.

**Comment by a10036gt** [comment]
The EV3 qyro sensor block write function  is SYS command "CMD_WRITE", but the SPIKE/RI use MESSAGE command with CMD_EXT_MODE to writing data, this function is omitted on EV3.
